-- Gym Crew recovered migration-history marker.
-- Remote migration: 202607140005_gym_mode_personal_split
--
-- The original SQL was not present in the repository when recovery began.
-- Its final schema effects are already folded into:
--   202607140001_initial_schema.sql
--
-- This intentionally contains no executable SQL. Keep the timestamp unchanged.
