-- OVRLD Pass 7 — ONE-TIME legacy product-data reset.
-- Run manually in Supabase SQL Editor only when you intentionally want every
-- existing account to re-enter onboarding. auth.users and profile identity/name/avatar are preserved.
-- This is deliberately NOT a migration so routine deploys cannot erase user data.

begin;

-- History / analytics derived from training.
delete from public.personal_records;
delete from public.workout_sessions;
delete from public.group_activity;

delete from public.weekly_schedule_days;

-- Body / goal journey.
delete from public.body_measurements;
delete from public.user_body_goals;

-- Gain Mode and nutrition. Child tables are removed first for installations
-- where foreign keys are restrictive rather than cascading.
delete from public.gain_calorie_adjustments;
delete from public.gain_nutrition_entries;
delete from public.gain_saved_meals;
delete from public.gain_mode_profiles;

-- Personal split data is regenerated by onboarding. Shared crew membership and
-- the account itself are preserved.
delete from public.split_days where owner_user_id is not null;

update public.profiles
set onboarding_completed_at = null,
    age_years = null,
    sex = null,
    training_level = null,
    weekly_training_days = null,
    split_setup_method = null,
    split_setup_completed_at = null;

commit;
